version: 2
jobs:
  users-api-tests:
    machine:
      services:
        - docker
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Docker Compose
          command: |
                curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - save_cache:
          paths:
            - ~/cache
          key: v1-dependencies-{{ checksum "build.gradle" }}
      # run tests!
      - run:
          name: Run Tests
          command: |
              cd users-api
              ./gradlew test
  feature-tests:
      machine:
        services:
          - docker
      working_directory: ~/repo
      steps:
        - checkout
        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
        - run:
            name: Install Docker Compose
            command: |
                  curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                  chmod +x ~/docker-compose
                  sudo mv ~/docker-compose /usr/local/bin/docker-compose
        - save_cache:
            paths:
              - ~/cache
            key: v1-dependencies-{{ checksum "build.gradle" }}
        # run tests!
        - run:
            name: Run Tests
            command: ./gradlew test
workflows:
  version: 2
  all-tests:
    jobs:
      - users-api-tests
      - feature-tests:
          requires:
            - users-api-tests